// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parduotuve.Data;

#nullable disable

namespace Parduotuve.Migrations
{
    [DbContext(typeof(StoreDataContext))]
    [Migration("20250302173224_starting")]
    partial class starting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Parduotuve.Data.Entities.Skin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChampionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChromaPrices")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChromaURLs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Chromas")
                        .HasColumnType("TEXT");

                    b.Property<string>("CinematicSplashUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Quote")
                        .HasColumnType("TEXT");

                    b.Property<string>("SplashUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChampionName = "Ahri",
                            ChromaPrices = "290;290;Loot Exclusive;290;290;Bundle Exclusive",
                            ChromaURLs = "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/8/82/Spirit_Blossom_Ahri_Ahri-versary.png[]https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/f/f1/Spirit_Blossom_Ahri_Aquamarine.png[]https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/b3/Spirit_Blossom_Ahri_Night_Blossom.png[]https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/bf/Spirit_Blossom_Ahri_Obsidian.png[]https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/b/be/Spirit_Blossom_Ahri_Pearl.png[]https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/7/76/Spirit_Blossom_Ahri_Rose_Quartz.png",
                            Chromas = "Ahri-versary;Aquamarine;Night Blossom;Obsidian;Pearl;Rose Quartz",
                            CinematicSplashUrl = "https://lol.fandom.com/wiki/Spirit_Blossom_Ahri?file=Skin_Splash_Spirit_Blossom_Ahri.jpg",
                            Name = "Spirit Blossom Ahri",
                            Price = 91.989999999999995,
                            Quote = "The famed Spirit of Salvation, and the fox all mortals are beckoned towards when their souls arrive to the spirit realm. A capricious,whimsical spirit who sees the fate of the living as a game of chase, she offers the chance for souls to find their final rest… but will not intervene if they stray from the path.",
                            SplashUrl = "https://static.wikia.nocookie.net/lolesports_gamepedia_en/images/d/de/Skin_Loading_Screen_Spirit_Blossom_Ahri.jpg"
                        });
                });

            modelBuilder.Entity("Parduotuve.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "guy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
